### ISSUE TITLE
question

### ISSUE THREAD

**Issue by SagittariusA22** [Sagittarius-22/Exercise#1]
昨天花很长时间写的一个轮播图，磕磕绊绊，低效，还有一些问题，麻烦你帮忙看看
1.鼠标移入下方   point   和点击左右切换图片过程中，定时调用还在执行，这样有冲突，如何解决（我尝试给 鼠标移入事件 里面添加一个 
 关闭定时调用 和 setA(）,然后鼠标移出又开启，可行但觉得麻烦）？
2..鼠标移出   point   和停止切换图片以后，无法自动恢复 定时调用与 setA( ),如何解决？
3.自己感觉整个代码写的有点复杂，感觉思路上有点欠缺或者有更好的优化空间，可否给出点建议，如果你觉得文字描述太麻烦，可以发语音给我，谢谢

**Comment by CocaColf** [comment]
有文件没有上传，没法看效果，简单阅读了以下代码。

> 问题 1

你的解决方法没有什么问题，我也是这样做

> 问题 2

- 你去查看几个有轮播图的网站，会发现这个问题不一定会解决
- 如果要解决唯一的方式也还是鼠标移出事件了，只有通过这个才知道是否在操作左右键

> 问题 3

你的思路没什么问题，在代码上初看有以下建议：

1. 全局变量全部提到最开始定义，方便阅读代码
2. 将操作封装
3. `setA() = null` 这是在做啥？

这里主要提一下 `将操作封装` 这一点：

在切换过程中，不管是定时器也好，手动切换也好，都会涉及到：index 计算、下方点的样式、容器的 left 设置、 index 的边界问题等，这些操作完全可以封装为一个函数，在需要的地方调用这个函数即可，这样的好处是如果有 bug 或需求变化的话只需要维护一个地方，所有相关的逻辑都在一处，代码也更清晰。

你甚至可以细化的封装出下一张，上一张等方法出来，这样不管有什么需求都很灵活。

**Comment by Sagittarius-22** [comment]
1、setA() = null 是想在鼠标移入时关闭下方setA（）函数，至于这个写法对不对有点蒙，反正生效了，哈哈哈

**Comment by SagittariusA22** [comment]
1、setA() = null 是想在鼠标移入时关闭下方setA（）函数，至于这个写法对不对有点蒙，反正生效了，哈哈哈
2、存在的问题我自己再看看，轮播图也还有其他的设计思路，后面如果还不清楚我再问你
3、操作封装不是很会，我练习几天可能会好点吧，两天练习发现，css和html基本操作问题不是很大，但是js练习的太少，还需要抓紧练一下找感觉。
4、目前这两天简单的js练习感觉非常吃力，不熟练，没思路，最后效果能完成80%以上吧。主要是觉得速度太慢，一天做不了几个简单的练习

**Comment by SagittariusA22** [comment]
@CocaColf
