### ISSUE TITLE
练习第四天

### ISSUE THREAD

**Issue by SagittariusA22** [Sagittarius-22/Exercise#2]
下列问题分为两个部分，技术学习和个人状态，有需要你提出建议的我会要求，没要求的部分你可建议可不建议

学习上
   1、四天的练习不是我从无到有一个人想出来和解决的，思路有参考网上各种资源，目前我面对一个新的小任务，基本还无法做到不参考任何东西写出来，问题主要在思路和有关方法的不熟练
   2、后两天的思维较前两天有一点点进步，主要体现在自己会想办法对参考案例的需求进一步完善，遇到的坎大部分会通过上网去解决，也有一些复杂的问题没解决，例如计算器的显示问题等等（发现把一个简单计算器的各种情况全部想到并且解决，对我来说是不简单且费时间的）
   3、这点需要你回复有关建议：
        状态描述：四天没做多少练习，比我预想的慢很多，目前做一个小练习还是盲人摸象的状态，只能一点点分析问题解决问题，无法做到一开始写就有全局认识的感觉，所以这周结束我觉得应该还无法找到较好的感觉；
        问题1：因此这种状态下，下周是继续练习，还是学习vue？我们之前的计划是一个星期练习，一个星期vue
        问题2：对做完的练习，你觉得是你想象中让我做的练习吗？这种练习你看得上眼么？以及你可以提出其他你想给的建议

个人状态（以下为非必须回复，只是需要讲述一下，我不能把所有的负面东西和我女朋友讲，要不然她压力也不小）
   1、应该是相当焦虑，不过能抗住，压力的来源主要是有时候在b站偶尔看到一些年轻博主（情况，学历和我差不多）描述目前前后端找工作好难，感觉下半年比上半年难很多，评论大部分也是消极的，所以我很怕脱产以后找不到工作，那个时候就是进退两难了，结果就是目前心里也没有定下来一往无前，转行这条路走到底。
   2、目前来说我肯定不是IT的天赋选手，虽然这几天过的举步维艰，一开始练习也是特别吃力，但是因为刚接触一个新鲜事物，不反感，不觉得很累，加上是有及时的正反馈吧。
    @总之不太但心我学不会，怕的是就业的问题，毕竟是专业、双非本科、年龄都没优势。

**Comment by CocaColf** [comment]
你刚开始写这种项目无法自己独立写出来这个是很正常的，多写写就会有感觉。写代码刚开始都是从 跟写->模仿->独立 写过来的。独立写是很重要的过程，也就是说一个「抄」一遍的项目后面需要「独立」写一遍。这个过程经历两三次基本就可以独立写了。

> 对做完的练习，你觉得是你想象中让我做的练习吗？这种练习你看得上眼么？以及你可以提出其他你想给的建议

你做的这几个项目都是不错的入门项目，没什么问题，而且你做得也挺精致的，所以样式上都要花很多时间。我建议接下来不要做这种独立的demo了，**做那种「带有交互功能的完整页面」**。比如现在这个 GitHub Issue 页面就还行，或者是留言板。它们都包括一个些交互：静态查看、编辑时会切换到另一个状态、删除、新增等等。

> 因此这种状态下，下周是继续练习，还是学习vue？我们之前的计划是一个星期练习，一个星期vue

我把你的问题换了一下顺序，第二个才回答这个问题。为什么呢，因为我建议你可以开始看 Vue 了。但是，在 Vue 之前做一个我上面说的「带有交互功能的完整页面」更好，因为这样可以让你理解「为什么使用 Vue」，或者说 Vue 带来了什么，同时对你后面会接触到的「前端工程化」这个概念有一定认识。 **所以你可以开始学 Vue 了，也可以先做一个上面说的项目后再学 Vue** ，然后你用原生 js 实现这个项目，用 Vue 实现这个项目，做个对比。

----

> 应该是相当焦虑，不过能抗住，压力的来源主要是有时候在b站偶尔看到一些年轻博主（情况，学历和我差不多）描述目前前后端找工作好难，感觉下半年比上半年难很多，评论大部分也是消极的，所以我很怕脱产以后找不到工作，那个时候就是进退两难了，结果就是目前心里也没有定下来一往无前，转行这条路走到底。

如果你决定尝试了，那就不要看那些贩卖焦虑的东西，已入行的人都看了心慌，更不用说你这种情况。不过看或者不看，确实能想象到后面找工作会比较辛苦的。我想从两个方面表达我的观点。

**第一，你的决心和规划**

现在你刚开始上路，如果有更好的打算和规划，那么回头来得及；如果转行到程序员上是目前能想到的最好打算，请坚持。

**第二，关于找工作**

这是很现实的事情，不管谁和你说沉下心来学习，都避免不了去想这个问题。我大学也不是学计算机的，我是大三下学期转行的，我学了四个月后拿到了大厂 offer，但是我一直觉得我是幸运占比较大。在此我也要提出一个看法，就是前端程序员都是自学出来的，因为大学不会教前端。那么对于找工作这件事只能尽人事听天命，站在几个月后的那个节点，你能做好什么呢？或者说如果我是一个招聘者，你什么可以打动我？

- 能够承担前端工作的能力。这个一方面是基础知识，另一方面是写代码（项目证明）。
- 学习能力。自学的背景，和自学后展现的能力，这种经历反应的是学习能力。
- 输出。这个也许是可选项。

我为什么要你开始用 GitHub，因为这上面可以展示你的代码，同时绿点记录了你的时间（经历）。因此它是上面几点的很好的载体。

输出很广泛：博客文章、开源项目贡献等。

所以如果你后面有一些项目，一两个一定规模且部门模块都亮点的项目，那我觉得问题不大，至少面试时可以聊的地方比较多。

> 目前来说我肯定不是IT的天赋选手，虽然这几天过的举步维艰，一开始练习也是特别吃力，但是因为刚接触一个新鲜事物，不反感，不觉得很累，加上是有及时的正反馈吧。

我也不是天赋选手，尤其是工作后见过天赋选手后更加认识到了这一点，而且这个行业许多人都不算真正热爱吧。正反馈是当然的，前端就是这点好，刷新一下浏览器正反馈就来了。

**Comment by SagittariusA22** [comment]
好的，今天去医院花了一天，生活总是会有一些其他的事情打断进度，哈哈哈
第一，有些东西只能我自己做决定，就不过多探讨了
第二，我后面写一个完整的页面吧，然后再开始vue @CocaColf
