### ISSUE TITLE
表单验证问题

### ISSUE THREAD

**Issue by SagittariusA22** [Sagittarius-22/Exercise#3]
1、这是我9.2写的，用时一天，90%独立完成的，html结构有一点点参考，源码已经上传（06-表单验证）；
2、为了封装函数，画了大量时间去各种尝试，最后是先写完，然后再封装，最后也算成了吧；
3、问题：帮我看看封装后的代码，看看格式，流程等等各方面是不是有需要注意的，你作为一个中年程序员，如果有低级错误，帮我纠正一下；
4、是不是一般写项目，html、css、js是分单独文件写的，我后续是否需要这样；
5、我平时和你沟通的所有东西，我的所言所行肯定像一个外行人，如果有，你就及时指正，我也好一点点养成良好习惯；
6、昨天的JS live server的问题已经解决，设置了live server的路径
7、感谢你抽出时间来带我入门，哈哈哈

**Comment by CocaColf** [comment]
1. 这个表单校验逻辑没什么问题，就是数据校验和 dom 操作，每个部分的输入框单独抽出来函数，而没有塞在一起，这个挺好的。
2. 你这个封装还不如封装前的。为什么呢？因为你现在这些逻辑，尤其是那个 `reset` 之类的函数，都是建立在你每个表单区域的 dom 结构相同的基础上，假如其中某一个表单的需求发生了改变，dom 结构变了，你那些所谓的 xxx[1], xxx[2] 全都不适用了。所以说每个输入框单独维护自己的逻辑反而更好
3. 看一下 JavaScript 的[解构赋值](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment)，把那些 xxx[1] 赋予更语义化的变量名称，不然别人看你代码 xxx[1] 根本不知道是啥，如果是 errorMessageText 就至少明白是错误文本显示
4. 你现在的 demo 比较简单，css、js 写一起无所谓。后面项目大了就需要分开，涉及到样式或者逻辑复用的问题
