### ISSUE TITLE
写issue时的一些疑问

### ISSUE THREAD

**Issue by SagittariusA22** [Sagittarius-22/Exercise#6]
![2](https://user-images.githubusercontent.com/112104249/188861999-3a8f3c9b-3666-4ce3-8233-34ff76cd61bf.png)
![1](https://user-images.githubusercontent.com/112104249/188862903-23bbc900-c45d-4541-80a0-e08d3d381852.png)

1、点击出现下拉列表，实际工作中是会在点击时去调用接口想后端请求数据，然后才实现的吗？不会直接在html中写好吗？这样就不用调接口了；
2、同样的，像京东淘宝等等这样大的列表呢？我看视频里面讲是会调接口向后端请求数据的

**Comment by SagittariusA22** [comment]
![3](https://user-images.githubusercontent.com/112104249/188863212-ffa0f8ac-944f-4142-97b2-562229fb71e0.png)
3、留言还可以重新编辑，这种实现的逻辑是怎样的呢？

**Comment by CocaColf** [comment]
> 下拉列表调接口与否的问题

这个要看需求的，如果列表项是固定的，那么可以在前端写好；但是一般情况下都不会是固定的。
1. 不管你前端写死与否，后端都会有一份对应的列表定义，毕竟你点击列表项它要拿数据给前端，所以后端也会有定义
2. 既然后端有定义了，那前端写死没有意义；而且写死了就不方便改变了，动态更新不方便做。你可以想一下，如果这个时候我列表下内容全要改，后端只需要修改一下配置文件整个就全改了；前端还需要改代码重新部署


> 留言还可以重新编辑

这个就是之前说的，每个留言都有一个 id，后端通过这个 id 可以在数据库找到它。

你编辑时把内容以及 id 传给后端，后端先用 id 找到这个留言，再用新内容替换一下就可以了
